spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: initial baseline

  application:
    name: kotlin_liargame

  jpa:
      show-sql: true
      hibernate:
          ddl-auto: create-drop

  h2:
      console:
          enabled: true  # H2 콘솔을 활성화합니다 (H2 콘솔은 H2 데이터베이스의 UI를 제공하는 도구)
          path: /h2-console  # H2 콘솔의 경로
#    datasource:
#        driver-class-name: org.h2.Driver  # 데이터베이스로 H2를 사용합니다.
#        url: jdbc:h2:mem:testdb  # H2 인메모리 데이터베이스 연결 경로
#        username: sa  # H2 접속 시 사용할 username 설정 (기본값 그대로 사용)
#        password:  # H2 접속 시 사용할 password 설정 (기본값 그대로 사용)

  datasource:
    url: ${SPRING_LOCAL_DATABASE_URL}
    username: ${SPRING_LOCAL_DATABASE_USERNAME}
    password: ${SPRING_LOCAL_DATABASE_PASSWORD}
    driver-class-name: ${SPRING_LOCAL_DATABASE_DRIVERCLASS}

  mvc:
      pathmatch:
          matching-strategy: ant_path_matcher

  session:
      store-type: redis
      redis:
        namespace: liargame:session
        flush-mode: on_save

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 3s
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 0



server:
    port: 20021
    servlet:
        session:
            timeout: 30m # 세션 타임아웃 설정

logging:
    level:
        root: INFO
        org.example.kotlin_liargame: DEBUG
        org.springframework.security: DEBUG

# JWT 관련 설정 모두 제거