spring:
  application:
    name: kotlin_liargame

  jpa:
      show-sql: true
      hibernate:
          ddl-auto: create
          # Set to 'validate' after fixing the schema
          # ddl-auto: validate
      properties:
        hibernate:
          # Performance optimizations
          jdbc:
            batch_size: 25
            batch_versioned_data: true
            fetch_size: 100
          order_inserts: true
          order_updates: true
          
          # Connection optimization - removed provider_disables_autocommit due to PostgreSQL conflict
          
          # Query cache settings
          cache:
            use_second_level_cache: false
            use_query_cache: false
          
          # Statistics (disable in production)
          generate_statistics: false
          
          # Default fetch settings
          default_batch_fetch_size: 16
          
          # Query timeout
          query:
            timeout: 30

  h2:
      console:
          enabled: true
          path: /h2-console

  datasource:
    url: ${SPRING_LOCAL_DATABASE_URL}
    username: ${SPRING_LOCAL_DATABASE_USERNAME}
    password: ${SPRING_LOCAL_DATABASE_PASSWORD}
    driver-class-name: ${SPRING_LOCAL_DATABASE_DRIVERCLASS}
    hikari:
      # auto-commit should be true for proper transaction management with Spring
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 20
      minimum-idle: 5
      pool-name: LiarGameHikariCP

  mvc:
      pathmatch:
          matching-strategy: ant_path_matcher

  session:
      store-type: redis
      redis:
        namespace: liargame:session
        flush-mode: immediate

  data:
    redis:
      host: ${REDIS_HOST:218.150.3.77}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 3s
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 10
          min-idle: 1

game:
  properties:
    # 플레이어 설정
    min-players: 3
    max-players: 15

    # 시간 제한 설정 (초 단위)
    turn-timeout-seconds: 60
    voting-time-seconds: 60
    defense-time-seconds: 60
    final-voting-time-seconds: 30
    topic-guess-time-seconds: 30

    # 채팅 설정
    post-round-chat-duration-seconds: 7
    max-message-length: 500

    # 게임 관리 설정
    max-game-duration-hours: 2
    session-extension-minutes: 5
    phase-transition-delay-seconds: 3

    # AI 판정 설정
    answer-similarity-threshold: 0.7

    # 게임 정리 설정
    game-cleanup-interval-seconds: 30

  state-storage:
    # Available strategies: redis, in_memory, hybrid
    strategy: hybrid
    hybrid-write-through: true

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  metrics:
    tags:
      application: "kotlin_liargame"

server:
  port: 20021
  servlet:
        session:
            timeout: 30m # 세션 타임아웃 설정
  address: 0.0.0.0

logging:
    level:
        root: INFO
        org.example.kotlin_liargame: DEBUG
        org.springframework.security: DEBUG
