spring:
  application:
    name: kotlin_liargame

  jpa:
      show-sql: true
      hibernate:
          ddl-auto: create-drop

  h2:
      console:
          enabled: true
          path: /h2-console

  datasource:
    url: ${SPRING_LOCAL_DATABASE_URL}
    username: ${SPRING_LOCAL_DATABASE_USERNAME}
    password: ${SPRING_LOCAL_DATABASE_PASSWORD}
    driver-class-name: ${SPRING_LOCAL_DATABASE_DRIVERCLASS}

  mvc:
      pathmatch:
          matching-strategy: ant_path_matcher

  session:
      store-type: redis
      redis:
        namespace: liargame:session
        flush-mode: on_save

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL:false}
      timeout: 3s
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 0

game:
  properties:
    # 플레이어 설정
    min-players: 3
    max-players: 15

    # 시간 제한 설정 (초 단위)
    turn-timeout-seconds: 60
    voting-time-seconds: 60
    defense-time-seconds: 60
    final-voting-time-seconds: 30
    topic-guess-time-seconds: 30

    # 채팅 설정
    post-round-chat-duration-seconds: 7
    max-message-length: 500

    # 게임 관리 설정
    max-game-duration-hours: 2
    session-extension-minutes: 5
    phase-transition-delay-seconds: 3

    # AI 판정 설정
    answer-similarity-threshold: 0.7

    # 게임 정리 설정
    game-cleanup-interval-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
  metrics:
    tags:
      application: "kotlin_liargame"

server:
    port: 20021
    servlet:
        session:
            timeout: 30m # 세션 타임아웃 설정

logging:
    level:
        root: INFO
        org.example.kotlin_liargame: DEBUG
        org.springframework.security: DEBUG
