// Action types for game state management
export const ACTION_TYPES = {
  // Loading actions
  SET_LOADING: 'SET_LOADING',
  SET_ERROR: 'SET_ERROR',
  
  // Auth actions
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
  
  // Room actions
  SET_ROOM_LIST: 'SET_ROOM_LIST',
  SET_CURRENT_ROOM: 'SET_CURRENT_ROOM',
  CLEAR_CURRENT_ROOM: 'CLEAR_CURRENT_ROOM',
  UPDATE_ROOM_IN_LIST: 'UPDATE_ROOM_IN_LIST',
  
  // Subject actions
  SET_SUBJECTS: 'SET_SUBJECTS',
  ADD_SUBJECT: 'ADD_SUBJECT',
  
  // WebSocket actions
  SET_SOCKET_CONNECTION: 'SET_SOCKET_CONNECTION',
  ADD_CHAT_MESSAGE: 'ADD_CHAT_MESSAGE',
  SET_CHAT_MESSAGES: 'SET_CHAT_MESSAGES',
  CLEAR_CHAT_MESSAGES: 'CLEAR_CHAT_MESSAGES',
  SET_ROOM_PLAYERS: 'SET_ROOM_PLAYERS',
  UPDATE_PLAYER_IN_ROOM: 'UPDATE_PLAYER_IN_ROOM',
  SET_CURRENT_TURN_PLAYER: 'SET_CURRENT_TURN_PLAYER',
  
  // Game logic actions
  SET_GAME_STATUS: 'SET_GAME_STATUS',
  SET_CURRENT_ROUND: 'SET_CURRENT_ROUND',
  SET_PLAYER_ROLE: 'SET_PLAYER_ROLE',
  SET_ASSIGNED_WORD: 'SET_ASSIGNED_WORD',
  SET_GAME_TIMER: 'SET_GAME_TIMER',
  SET_VOTING_RESULTS: 'SET_VOTING_RESULTS',
  SET_VOTING_DATA: 'SET_VOTING_DATA',
  SET_VOTING_PROGRESS: 'SET_VOTING_PROGRESS',
  SET_MY_VOTE: 'SET_MY_VOTE',
  SET_GAME_RESULTS: 'SET_GAME_RESULTS',
  SET_ACCUSED_PLAYER: 'SET_ACCUSED_PLAYER',
  SET_DEFENDING_PLAYER: 'SET_DEFENDING_PLAYER',
  SET_DEFENSE_TEXT: 'SET_DEFENSE_TEXT',
  SET_SURVIVAL_VOTING_PROGRESS: 'SET_SURVIVAL_VOTING_PROGRESS',
  SET_MY_SURVIVAL_VOTE: 'SET_MY_SURVIVAL_VOTE',
  SET_WORD_GUESS_RESULT: 'SET_WORD_GUESS_RESULT',
  SET_FINAL_GAME_RESULT: 'SET_FINAL_GAME_RESULT',
  SET_MODERATOR_MESSAGE: 'SET_MODERATOR_MESSAGE',
  
  // Navigation actions
  SET_CURRENT_PAGE: 'SET_CURRENT_PAGE'
}

// Game status constants
export const GAME_STATUS = {
  WAITING: 'WAITING',
  SPEAKING: 'SPEAKING',
  VOTING: 'VOTING',
  RESULTS: 'RESULTS',
  FINISHED: 'FINISHED'
}

// Player role constants
export const PLAYER_ROLES = {
  LIAR: 'LIAR',
  CITIZEN: 'CITIZEN'
}

// Game winner constants
export const GAME_WINNERS = {
  LIAR: 'LIAR',
  CITIZEN: 'CITIZEN'
}

// Page constants
export const PAGES = {
  LOBBY: 'lobby',
  ROOM: 'room'
}

// Loading state keys
export const LOADING_KEYS = {
  ROOMS: 'rooms',
  ROOM: 'room',
  AUTH: 'auth',
  SUBJECTS: 'subjects',
  SOCKET: 'socket',
  CHAT_HISTORY: 'chatHistory'
}

// Error state keys
export const ERROR_KEYS = {
  ROOMS: 'rooms',
  ROOM: 'room',
  AUTH: 'auth',
  SUBJECTS: 'subjects',
  SOCKET: 'socket'
}